[package]
name = "grayguava-desktop"
version = "0.1.0"
description = "GrayGuava Desktop"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
